version: '3.8'

services:
  server:
    build: ./server
    expose:
      - ${APP_SERVER_PORT}
    environment: 
      API_HOST: ${API_HOST}
      APP_SERVER_PORT: ${APP_SERVER_PORT}
    ports: 
      - ${APP_SERVER_PORT}:${APP_SERVER_PORT}
    volumes:
      - ./server:/build
    command: /dist/main
  client:
    build: ./client
    environment: 
      - REACT_APP_PORT=${REACT_APP_PORT}
    expose: 
      - ${REACT_APP_PORT}
    ports: 
      - ${REACT_APP_PORT}:${REACT_APP_PORT}
    volumes:
      - ./client/src:/app/src
      - ./client/public:/app/public
    links:
      - server
    command: npm start